import crypto from "crypto";
import { AccountDAODatabase } from "../../src/infra/dao/AccountDAO";
import Registry from "../../src/infra/di/Registry";
import { PgPromiseAdapter } from "../../src/infra/database/DatabaseConnection";
import { AccountAssetDAODatabase } from "../../src/infra/dao/AccountAssetDAO";
import { AccountRepositoryDatabase, AccountRepositoryORM } from "../../src/infra/repository/AccountRepository";
import Account from "../../src/domain/Account";
import ORM from "../../src/infra/orm/ORM";

test("Deve persistir uma conta", async () => {
    const connection = new PgPromiseAdapter();
    Registry.getInstance().provide("databaseConnection", connection);
    Registry.getInstance().provide("orm", new ORM());
    // Registry.getInstance().provide("accountDAO", new AccountDAODatabase);
    // Registry.getInstance().provide("accountAssetDAO", new AccountAssetDAODatabase);
    // const accountRepository = new AccountRepositoryDatabase();
    const accountRepository = new AccountRepositoryORM();
    const account = Account.create("John Doe", "john.doe@gmail.com", "87748248800", "aseQRT987");
    account.deposit("USD", 10000);
    account.deposit("BTC", 100);
    await accountRepository.save(account);
    const savedAccount = await accountRepository.getById(account.accountId);
    expect(savedAccount.accountId).toBe(account.accountId);
    expect(savedAccount.getName()).toBe(account.getName());
    expect(savedAccount.getEmail()).toBe(account.getEmail());
    expect(savedAccount.getDocument()).toBe(account.getDocument());
    expect(savedAccount.getPassword()).toBe(account.getPassword());
    expect(savedAccount.balances).toHaveLength(2);
    expect(savedAccount.balances[0].quantity).toBe(10000);
    expect(savedAccount.balances[1].quantity).toBe(100);
    await connection.close();
});